# Generated by Django 3.2.8 on 2021-10-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100)),
                ('password', models.TextField(blank=True)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=70)),
                ('countryCode', models.CharField(max_length=5)),
                ('contactNumber', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=300)),
                ('skills', models.JSONField(default='{"skills" : [] }')),
                ('projects', models.JSONField(default='{"projects" : [] }')),
                ('linkGithub', models.TextField(blank=True)),
                ('linkLinkedIn', models.TextField(blank=True)),
                ('linkExtra', models.JSONField(default='{"links" : [] }')),
                ('dateJoined', models.DateField()),
                ('lastLogin', models.DateField()),
            ],
        ),
    ]
