# Generated by Django 3.2.8 on 2021-11-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postedjob',
            name='appliedPeople',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userappliedjobs',
            name='appliedTo',
            field=models.TextField(blank=True, default=''),
        ),
    ]
