# Generated by Django 3.2.8 on 2021-10-19 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='lastLogin',
        ),
    ]
