# Generated by Django 3.2.8 on 2021-11-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20211115_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='linkExtra',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='projects',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=models.TextField(blank=True, default=''),
        ),
    ]
