# Generated by Django 3.2.8 on 2021-11-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_compdata_postedjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postedjob',
            name='reqSkill',
            field=models.JSONField(default='{"skills" : [] }'),
        ),
    ]
